"""Game model upgreade

Revision ID: bce08236b692
Revises: 08220d19f09b
Create Date: 2025-04-18 00:00:31.080101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce08236b692'
down_revision: Union[str, None] = '08220d19f09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'submissions', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'game_id')
    # ### end Alembic commands ###
